### ISSUE TITLE
Some running questions 

### ISSUE THREAD

**Issue by DOGEE7** [xiangwang1223/knowledge_graph_attention_network#17]
Hello, thank you very much for your contribution, I tried to run your example, but I met some problems. The example is as follows:
>python Main.py --dataset last-fm  --pretrain -1 
The error is as follows:
#params: 12049088
without pretraining.
What's the problem? How can I solve it?

**Comment by blldd** [comment]
I also meet some problems:

#params: 12059472
without pretraining.
Traceback (most recent call last):
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 1 of dimension 0 out of bounds.
	 [[{{node strided_slice_1}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_Placeholder_4_0_4/_5, ConstantFolding/gradients/l2_normalize_grad/BroadcastGradientArgs-bcastargs-1, strided_slice_1/stack_1, ConstantFolding/gradients/l2_normalize_grad/BroadcastGradientArgs-bcastargs-1)]]
	 [[{{node add_15/_39}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4582_add_15", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sensetime/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/sensetime/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/sensetime/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/sensetime/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/sensetime/pycharm_workspace/Emb4RS/KG/knowledge_graph_attention_network/Model/Main.py", line 244, in <module>
    _, batch_loss, batch_base_loss, batch_kge_loss, batch_reg_loss = model.train(sess, feed_dict=feed_dict)
  File "/home/sensetime/pycharm_workspace/Emb4RS/KG/knowledge_graph_attention_network/Model/KGAT.py", line 423, in train
    return sess.run([self.opt, self.loss, self.base_loss, self.kge_loss, self.reg_loss], feed_dict)
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 1 of dimension 0 out of bounds.
	 [[node strided_slice_1 (defined at /home/sensetime/pycharm_workspace/Emb4RS/KG/knowledge_graph_attention_network/Model/KGAT.py:286)  = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_Placeholder_4_0_4/_5, ConstantFolding/gradients/l2_normalize_grad/BroadcastGradientArgs-bcastargs-1, strided_slice_1/stack_1, ConstantFolding/gradients/l2_normalize_grad/BroadcastGradientArgs-bcastargs-1)]]
	 [[{{node add_15/_39}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4582_add_15", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'strided_slice_1', defined at:
  File "/home/sensetime/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/sensetime/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/sensetime/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/sensetime/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/sensetime/pycharm_workspace/Emb4RS/KG/knowledge_graph_attention_network/Model/Main.py", line 92, in <module>
    model = KGAT(data_config=config, pretrain_data=pretrain_data, args=args)
  File "/home/sensetime/pycharm_workspace/Emb4RS/KG/knowledge_graph_attention_network/Model/KGAT.py", line 36, in __init__
    self._build_model_phase_I()
  File "/home/sensetime/pycharm_workspace/Emb4RS/KG/knowledge_graph_attention_network/Model/KGAT.py", line 162, in _build_model_phase_I
    self.ua_embeddings, self.ea_embeddings = self._create_bi_interaction_embed()
  File "/home/sensetime/pycharm_workspace/Emb4RS/KG/knowledge_graph_attention_network/Model/KGAT.py", line 286, in _create_bi_interaction_embed
    ego_embeddings = tf.nn.dropout(ego_embeddings, 1 - self.mess_dropout[k])
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 525, in _slice_helper
    name=name)
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 691, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8522, in strided_slice
    name=name)
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/sensetime/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): slice index 1 of dimension 0 out of bounds.
	 [[node strided_slice_1 (defined at /home/sensetime/pycharm_workspace/Emb4RS/KG/knowledge_graph_attention_network/Model/KGAT.py:286)  = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_Placeholder_4_0_4/_5, ConstantFolding/gradients/l2_normalize_grad/BroadcastGradientArgs-bcastargs-1, strided_slice_1/stack_1, ConstantFolding/gradients/l2_normalize_grad/BroadcastGradientArgs-bcastargs-1)]]
	 [[{{node add_15/_39}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4582_add_15", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


Thanks for your time:)

**Comment by viviqi** [comment]
If there is no prompt showing end the process, the code may still be running, you need to wait for a while. It is slow to train the dataset, as least on my computer.
