### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Tijana37** [xiangwang1223/knowledge_graph_attention_network#59]
Traceback (most recent call last):
  File "Main.py", line 9, in <module>
    from utility.batch_test import *
  File "Model/utility/batch_test.py", line 42, in <module>
    data_generator = KGAT_loader(args=args, path=args.data_path + args.dataset)
  File "Model/utility/loader_kgat.py", line 16, in __init__
    super().__init__(args, path)
  File "Model/utility/load_data.py", line 38, in __init__
    self.kg_data, self.kg_dict, self.relation_dict = self._load_kg(kg_file)
  File "Model/utility/load_data.py", line 81, in _load_kg
    kg_np = np.loadtxt(file_name, dtype=np.int32)
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 1092, in loadtxt
    first_line = next(fh)
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 11: invalid start byte**

**Comment by Tolucaa** [comment]
hey, how did you resolve this issue?
